### ISSUE TITLE
開発・本番環境を切り替えられるようにする

### ISSUE THREAD

**Issue by orino-gif** [orino-gif/myori#14]

**Comment by orino-gif** [comment]
現在のECインスタンスを本番用に変更。
その後、新しく開発用インスタンスを本番用のバックアップ元からリストア。

**Comment by orino-gif** [comment]
Railsの開発環境・テスト環境・本番環境の学習。
https://pikawaka.com/rails/env

**Comment by orino-gif** [comment]
gemの自作方法の資料を参照
https://qiita.com/9sako6/items/72994b8b1c00af4e61fe

**Comment by orino-gif** [comment]
tail -f でログをリアルタイム表示

![tail実行後にリクエストした結果](https://user-images.githubusercontent.com/74188756/102677153-65ba7700-41e4-11eb-8e99-f4a4ede92961.png)

**Comment by orino-gif** [comment]
アセットプリコンパイルでエラーを確認。
[rio@ip-172-31-40-58 myori]$ bundle exec rake assets:precompile RAILS_ENV=production
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.05s.
rake aborted!
Sass::SyntaxError: Invalid CSS after "... -22px; top 40%": expected "{", was "; margin-top: 0px;"
(sass):86
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:1308:in `expected'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:1238:in `expected'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:1233:in `tok!'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:688:in `block'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:758:in `declaration_or_ruleset'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:708:in `block_child'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:700:in `block_contents'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:689:in `block'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:681:in `ruleset'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:707:in `block_child'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:700:in `block_contents'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:137:in `stylesheet'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:41:in `parse'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/engine.rb:414:in `_to_tree'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/engine.rb:290:in `render'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:48:in `call'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:28:in `call'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:67:in `block (3 levels) in define'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:66:in `block (2 levels) in define'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/rio/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/home/rio/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

**Comment by orino-gif** [comment]
application.cssをすべてコメントにすると、
エラーが発生しない事を確認。

**Comment by orino-gif** [comment]
※動的にプリコンパイルをする方法もあるようです。


$ vi config/environments/production.rb

config.assets.compile = true

**Comment by orino-gif** [comment]
アセットコンパイル後にCSSファイルが出力されない問題が露呈。
別チケットを作成

**Comment by orino-gif** [comment]
AWSに、現在の本番環境ECインスタンスのコピーを作成。
コピーしたインスタンスは開発用とする。

**Comment by orino-gif** [comment]
本番環境で画像が表示されないエラーが発生。
アセットパイプラインで画像変換が実行されていない可能性有。
対応中。

**Comment by orino-gif** [comment]
以下のサイトを参考にアセットパイプラインの問題を切り分け
https://qiita.com/metheglin/items/c5c756246b7afbd34ae2

**Comment by orino-gif** [comment]
images返還後の画像のファイル名が変更されている。
その事を中心に調べる。

**Comment by orino-gif** [comment]
アセットコンパイル後の
person
scene
site-part
削除。

**Comment by orino-gif** [comment]
プリコンパイル済みのアセット先を確認
irb(main):001:0> Rails.application.config.assets.prefix
=> "/assets"

**Comment by orino-gif** [comment]
33   # Do not fallback to assets pipeline if a precompiled asset is missed.
 34   config.assets.compile = true
で一旦進める。

**Comment by orino-gif** [comment]
develop用インスタンス i-071a639b3b1ca05fd
を作成

**Comment by orino-gif** [comment]
develop用インスタンス接続先54.150.42.23
接続確認完了

**Comment by orino-gif** [comment]
バックアップ設定完了。
明日に状態確認。

**Comment by orino-gif** [comment]
開発から本番環境へのデプロイを行う。
ファイルが開発環境から本番環境へ移る事を確認。
