### ISSUE TITLE
nginxとの連携

### ISSUE THREAD

**Issue by orino-gif** [orino-gif/myori#18]
railsとnginxを連携させて、port80からrailsへアクセスできるようにする。

**Comment by orino-gif** [comment]
ブランチ nginx-cmbを作成

**Comment by orino-gif** [comment]
56サーバ‐と内容を合わせる

**Comment by orino-gif** [comment]
もしサーバーをデーモンとして実行したい場合は-dオプションを付けましょう

$ bundle exec puma -d

**Comment by orino-gif** [comment]
Linux2でrails sを実行すると、以下のエラーがでる。
[rio@ip-172-31-40-58 myori]$ rails s
=> Booting Puma
=> Rails 5.1.7 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.12.6 (ruby 2.7.2-p137), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
Exiting
Traceback (most recent call last):
        22: from bin/rails:9:in `<main>'
        21: from bin/rails:9:in `require'
        20: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
        19: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/railties-5.1.7/lib/rails/command.rb:44:in `invoke'
        18: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/railties-5.1.7/lib/rails/command/base.rb:63:in `perform'
        17: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        16: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        15: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        14: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:130:in `perform'
        13: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:130:in `tap'
        12: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:135:in `block in perform'
        11: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/railties-5.1.7/lib/rails/commands/server/server_command.rb:44:in `start'
        10: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
         9: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/puma-3.12.6/lib/rack/handler/puma.rb:73:in `run'
         8: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/puma-3.12.6/lib/puma/launcher.rb:186:in `run'
         7: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/puma-3.12.6/lib/puma/single.rb:98:in `run'
         6: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/puma-3.12.6/lib/puma/runner.rb:153:in `load_and_bind'
         5: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/puma-3.12.6/lib/puma/binder.rb:90:in `parse'
         4: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/puma-3.12.6/lib/puma/binder.rb:90:in `each'
         3: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/puma-3.12.6/lib/puma/binder.rb:141:in `block in parse'
         2: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/puma-3.12.6/lib/puma/binder.rb:371:in `add_unix_listener'
         1: from /home/rio/myori/vendor/bundle/ruby/2.7.0/gems/puma-3.12.6/lib/puma/binder.rb:371:in `new'
/home/rio/myori/vendor/bundle/ruby/2.7.0/gems/puma-3.12.6/lib/puma/binder.rb:371:in `initialize': No such file or directory - connect(2) for home/rio/myori/tmp/sockets/puma.sock (Errno::ENOENT)

**Comment by orino-gif** [comment]
nginxは80でアクセス可能。
railsは3000でアクセス可能。

**Comment by orino-gif** [comment]
puma.rbでポート3000指定すると、rails sでも起動（両方)

**Comment by orino-gif** [comment]
nginx/conf.d/puma.rbパーミッションのオーナーがroot。
rioに変更。
同ファイル名がpuma.rb。
puma.confに変更。

**Comment by orino-gif** [comment]
nginxリスタート時にエラー発生。
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2020-12-16 22:19:55 JST; 1min 10s ago
  Process: 13639 ExecReload=/bin/kill -s HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 19945 ExecStart=/usr/sbin/nginx (code=exited, status=0/SUCCESS)
  Process: 25874 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=1/FAILURE)
  Process: 25873 ExecStartPre=/usr/bin/rm -f /run/nginx.pid (code=exited, status=0/SUCCESS)
 Main PID: 19947 (code=killed, signal=KILL)

Dec 16 22:19:54 ip-172-31-40-58.ap-northeast-1.compute.internal systemd[1]: Starting The nginx HTTP and reverse proxy server...
Dec 16 22:19:55 ip-172-31-40-58.ap-northeast-1.compute.internal nginx[25874]: nginx: [warn] server name "http://ec2-18-179-150-100.ap-n...nf:9
Dec 16 22:19:55 ip-172-31-40-58.ap-northeast-1.compute.internal nginx[25874]: nginx: [emerg] could not build server_names_hash, you sho...: 64
Dec 16 22:19:55 ip-172-31-40-58.ap-northeast-1.compute.internal nginx[25874]: nginx: configuration file /etc/nginx/nginx.conf test failed
Dec 16 22:19:55 ip-172-31-40-58.ap-northeast-1.compute.internal systemd[1]: nginx.service: control process exited, code=exited status=1
Dec 16 22:19:55 ip-172-31-40-58.ap-northeast-1.compute.internal systemd[1]: Failed to start The nginx HTTP and reverse proxy server.
Dec 16 22:19:55 ip-172-31-40-58.ap-northeast-1.compute.internal systemd[1]: Unit nginx.service entered failed state.
Dec 16 22:19:55 ip-172-31-40-58.ap-northeast-1.compute.internal systemd[1]: nginx.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
log参照予定。

**Comment by orino-gif** [comment]
[rio@ip-172-31-40-58 myori]$ sudo systemctl -l status nginx
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2020-12-16 22:32:20 JST; 3min 12s ago
  Process: 13639 ExecReload=/bin/kill -s HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 19945 ExecStart=/usr/sbin/nginx (code=exited, status=0/SUCCESS)
  Process: 25956 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=1/FAILURE)
  Process: 25955 ExecStartPre=/usr/bin/rm -f /run/nginx.pid (code=exited, status=0/SUCCESS)
 Main PID: 19947 (code=killed, signal=KILL)

Dec 16 22:32:20 ip-172-31-40-58.ap-northeast-1.compute.internal systemd[1]: Starting The nginx HTTP and reverse proxy server...
Dec 16 22:32:20 ip-172-31-40-58.ap-northeast-1.compute.internal nginx[25956]: nginx: [warn] server name "http://ec2-18-179-150-100.ap-northeast-1.compute.amazonaws.com" has suspicious symbols in /etc/nginx/conf.d/puma.conf:9
Dec 16 22:32:20 ip-172-31-40-58.ap-northeast-1.compute.internal nginx[25956]: nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
Dec 16 22:32:20 ip-172-31-40-58.ap-northeast-1.compute.internal nginx[25956]: nginx: configuration file /etc/nginx/nginx.conf test failed
Dec 16 22:32:20 ip-172-31-40-58.ap-northeast-1.compute.internal systemd[1]: nginx.service: control process exited, code=exited status=1
Dec 16 22:32:20 ip-172-31-40-58.ap-northeast-1.compute.internal systemd[1]: Failed to start The nginx HTTP and reverse proxy server.
Dec 16 22:32:20 ip-172-31-40-58.ap-northeast-1.compute.internal systemd[1]: Unit nginx.service entered failed state.
Dec 16 22:32:20 ip-172-31-40-58.ap-northeast-1.compute.internal systemd[1]: nginx.service failed.

**Comment by orino-gif** [comment]
目的はnginxを挟んで処理を自動化させる事なので、
portを変更すれば、済む話ではない。

**Comment by orino-gif** [comment]
nginxが開始できないエラーが発生。

**Comment by orino-gif** [comment]
nginxはアクセスが発生するとそのクライアント名やHTTPの要求内容を
ログとして/var/log/nginxに保存。

**Comment by orino-gif** [comment]
ifconfig | grep "inet "で
ipアドレスのみ確認。

**Comment by orino-gif** [comment]
b 0.0.0.0 は、そのホストが持つ全てのIPアドレスをバインディングするという意味。
